config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users do
    member do
      get 'p5', to: 'users#p5_balance'
      get 'rewards', to: 'reward_histories#index'
    end
    resources :reward_histories, only: %i[new create destroy]
  end
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reward_history.rb
# frozen_string_literal: true

class RewardHistory < ApplicationRecord
  belongs_to :giver, class_name: 'User', foreign_key: :given_by
  belongs_to :receiver, class_name: 'User', foreign_key: :given_to

  validates :points, numericality: { greater_than: 0, less_than_or_equal_to: 100 }

  after_create :update_balances_on_create
  after_destroy :update_balances_on_destroy

  private

  def update_balances_on_create
    giver.update!(p5_balance: giver.p5_balance - points)
    receiver.update!(reward_balance: (receiver.reward_balance || 0) + points)
  end

  def update_balances_on_destroy
    giver.update!(p5_balance: giver.p5_balance + points)
    receiver.update!(reward_balance: receiver.reward_balance - points)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :given_rewards, class_name: 'RewardHistory', foreign_key: :given_by
  has_many :received_rewards, class_name: 'RewardHistory', foreign_key: :given_to

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reward_histories_controller.rb
class RewardHistoriesController < ApplicationController
  before_action :set_user, only: %i[index new create]
  before_action :set_reward_history, only: :destroy

  def index
    @rewards = @user.given_rewards
  end

  def new
    @other_users = User.where.not(id: @user.id)
    @reward_history = RewardHistory.new
  end

  def create
    @reward_history = @user.given_rewards.build(reward_history_params)

    if @user.p5_balance < @reward_history.points
      redirect_to new_user_reward_history_path(@user), alert: 'Not enough P5 points'
      return
    end

    if @reward_history.save
      redirect_to rewards_user_path(@user), notice: 'Reward given successfully'
    else
      render :new, alert: 'Error: Unable to give reward'
    end
  end

  def destroy
    @reward_history.destroy
    redirect_to p5_user_path(@reward_history.giver),
                notice: 'Reward history deleted successfully'
  end

  private

  def set_user
    @user = User.find(params[:user_id] || params[:id])
  end

  def set_reward_history
    @reward_history = RewardHistory.find(params[:id])
  end

  def reward_history_params
    params.require(:reward_history).permit(:points).merge(given_to: params[:reward_history][:receiver_id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit show update p5_balance]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def show; end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def p5_balance; end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :p5_balance)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeerfivesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reward_histories/index.html.erb
<h1>Reward History</h1>
<p>Rewards Balance: <%= @user.reward_balance %></p>
<table>
  <tr>
    <th>#</th>
    <th>Date-Time</th>
    <th>Rewards Received</th>
    <th>User Name</th>
  </tr>
  <% @user.received_rewards.each_with_index do |reward, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= reward.created_at %></td>
      <td><%= reward.points %></td>
      <td><%= reward.giver.name %></td> <!-- Show giver's name -->
    </tr>
  <% end %>
</table>

<table>
  <tr>
    <th>#</th>
    <th>Date-Time</th>
    <th>Rewards Send</th>
    <th>User Name</th>
  </tr>
  <% @user.given_rewards.each_with_index do |reward, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= reward.created_at %></td>
      <td><%= reward.points %></td>
      <td><%= reward.receiver.name %></td> <!-- Show giver's name -->
      <td>
        <%= button_to 'Revoke Rewards',
                    user_reward_history_path(@user, reward),
                    method: :delete,
                    data: { confirm: 'Are you sure you want to revoke this reward?' },
                    class: 'button btn btn-danger' %>
      </td>
    </tr>

  <% end %>
</table>

app/views/reward_histories/new.html.erb
<h1>New Reward</h1>

<%= form_with(model: @reward_history, url: user_reward_histories_path(@user), local: true) do |f| %>
  <div>
    <%= f.label :receiver_id, 'Select Receiver' %>
    <%= f.select :receiver_id, options_from_collection_for_select(@other_users, :id, :name), prompt: 'Choose a user' %>
  </div>
  <div>
    <%= f.label :points, 'Points to Reward' %>
    <%= f.number_field :points, min: 1, max: @user.p5_balance, value: 1 %>
  </div>
  <p>P5 Balance: <%= @user.p5_balance %></p>

  <div>
    <%= f.submit 'Give Reward' %>
  </div>
<% end %>

<%= link_to 'Cancel', user_reward_histories_path(@user) %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :p5_balance %>
    <%= form.number_field :p5_balance %>
  </div>
  <%= form.submit 'Save' %>
  <%= link_to 'Cancel', users_path %>
<% end %>

app/views/users/edit.html.erb
<h1>User Details</h1>

<%= form_with(model: @user, url: user_path(@user), method: :patch, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit 'Save' %>
<% end %>

<p>
  <%= link_to "P5 Balance: #{@user.p5_balance}", p5_user_path(@user) %>
</p>
<p>
  <%= link_to "Rewards Balance: #{@user.reward_balance}", rewards_user_path(@user) %>
</p>

<%= link_to 'Back to Users List', users_path %>

app/views/users/index.html.erb
<h1>Users List</h1>
<%= link_to 'Create New User', new_user_path %>
<table>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>P5 Balance</th>
    <th>Reward Balance</th>
    <th>Actions</th>
  </tr>
  <% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= user.name %></td>
      <td><%= user.p5_balance %></td>
      <td><%= user.reward_balance %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back to Users', users_path %>

app/views/users/p5_balance.html.erb
<h1>P5 Balance</h1>
<p><strong>User:</strong> <%= @user.name %></p>
<p><strong>P5 Balance:</strong> <%= @user.p5_balance %></p>
<td><%= link_to 'Send Rewards', new_user_reward_history_path(@user), class: 'button' %></td>

<%= link_to 'Back to User', user_path(@user) %>

app/views/users/show.html.erb
<h1>User Details</h1>

<%= form_with(model: @user, url: user_path(@user), method: :patch, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit 'Save' %>
<% end %>

<p>
  <%= link_to "P5 Balance: #{@user.p5_balance}", p5_user_path(@user) %>
</p>
<p>
  <%= link_to "Rewards Balance: #{@user.reward_balance}", rewards_user_path(@user) %>
</p>

<%= link_to 'Back to Users List', users_path %>